# Generated by Django 5.0.1 on 2024-01-12 05:40

import django.db.models.deletion
from django.db import migrations, models

import boapp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_idx', boapp.models.PowerOfTwoAutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_idx', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_department_num', models.IntegerField()),
                ('doctor_non_insured_treatment_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_idx', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NonInsuredTreatment',
            fields=[
                ('treatment_idx', boapp.models.PowerOfTwoAutoField(primary_key=True, serialize=False)),
                ('treatment_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('biz_open_time', models.TimeField()),
                ('biz_close_time', models.TimeField()),
                ('lunch_start_time', models.TimeField()),
                ('lunch_end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boapp.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boapp.hospital'),
        ),
    ]
