# Generated by Django 5.0.1 on 2024-01-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='biz_close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='biz_open_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='lunch_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='lunch_start_time',
            field=models.TimeField(null=True),
        ),
    ]
