# Generated by Django 5.0.1 on 2024-01-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boapp', '0002_alter_businesshours_biz_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='day_of_week',
            field=models.IntegerField(),
        ),
    ]
