# Generated by Django 5.0.1 on 2024-01-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boapp', '0003_alter_businesshours_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_idx', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
            ],
        ),
    ]
