# Generated by Django 5.0.1 on 2024-01-12 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('boapp', '0004_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRequest',
            fields=[
                ('medical_request_idx', models.AutoField(primary_key=True, serialize=False)),
                ('request_datetime', models.DateTimeField()),
                ('request_expire_datetime', models.DateTimeField()),
                ('request_accept_yn', models.CharField(default='N', max_length=1)),
                ('doctor_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boapp.doctor')),
                ('patient_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boapp.patient')),
            ],
        ),
    ]
