# Generated by Django 5.0.1 on 2024-01-12 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrequest',
            old_name='doctor_idx',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='medicalrequest',
            old_name='patient_idx',
            new_name='patient',
        ),
    ]
