# Generated by Django 5.0.1 on 2024-01-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foapp', '0002_rename_doctor_idx_medicalrequest_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrequest',
            name='req_able',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
